"""create user table

Revision ID: 298a6a4afcad
Revises: 
Create Date: 2026-06-08 10:30:42.241876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '298a6a4afcad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('nameUser', sa.String(length=100), nullable=True),
    sa.Column('emailUser', sa.String(length=30), nullable=True),
    sa.Column('passwordUser', sa.String(length=10), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idUser')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
