"""rombak database

Revision ID: 831dea9186b7
Revises: 8c56810c395c
Create Date: 2026-06-14 23:18:11.866118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '831dea9186b7'
down_revision: Union[str, Sequence[str], None] = '8c56810c395c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preprocessing_result')
    op.drop_table('preprocessing_training')
    op.drop_table('parameter_training')
    op.drop_table('model')
    op.add_column('dataset', sa.Column('preprocessingResultPath', sa.String(length=999), nullable=True))
    op.add_column('ratio_data_split', sa.Column('epochs', sa.String(), nullable=True))
    op.add_column('ratio_data_split', sa.Column('batchSize', sa.String(), nullable=True))
    op.add_column('ratio_data_split', sa.Column('learningRate', sa.Float(), nullable=True))
    op.add_column('ratio_data_split', sa.Column('accuracy', sa.Float(), nullable=True))
    op.add_column('ratio_data_split', sa.Column('precision', sa.Float(), nullable=True))
    op.add_column('ratio_data_split', sa.Column('recall', sa.Float(), nullable=True))
    op.add_column('ratio_data_split', sa.Column('f1score', sa.Float(), nullable=True))
    op.add_column('ratio_data_split', sa.Column('bestRatio', sa.Boolean(), nullable=True))
    op.add_column('ratio_data_split', sa.Column('updatedAt', sa.DateTime(), nullable=True))
    op.alter_column('ratio_data_split', 'trainRatio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=99),
               existing_nullable=True)
    op.drop_column('ratio_data_split', 'testRatio')
    op.drop_column('ratio_data_split', 'valRatio')
    op.add_column('training', sa.Column('idDataset', sa.Integer(), nullable=True))
    op.add_column('training', sa.Column('modelName', sa.String(length=99), nullable=True))
    op.add_column('training', sa.Column('LSTMUnits1', sa.Integer(), nullable=True))
    op.add_column('training', sa.Column('LSTMUnits2', sa.Integer(), nullable=True))
    op.add_column('training', sa.Column('dropout1', sa.Float(), nullable=True))
    op.add_column('training', sa.Column('dropout2', sa.Float(), nullable=True))
    op.add_column('training', sa.Column('denseUnits', sa.Integer(), nullable=True))
    op.add_column('training', sa.Column('kFold', sa.Integer(), nullable=True))
    op.add_column('training', sa.Column('epochs', sa.Integer(), nullable=True))
    op.add_column('training', sa.Column('batchSize', sa.Integer(), nullable=True))
    op.add_column('training', sa.Column('learningRate', sa.Float(), nullable=True))
    op.add_column('training', sa.Column('confusionMatrix', sa.JSON(), nullable=True))
    op.add_column('training', sa.Column('weightedAverage', sa.Float(), nullable=True))
    op.add_column('training', sa.Column('macroAverage', sa.Float(), nullable=True))
    op.add_column('training', sa.Column('trainLoss', sa.Float(), nullable=True))
    op.add_column('training', sa.Column('valLoss', sa.Float(), nullable=True))
    op.add_column('training', sa.Column('mcc', sa.Float(), nullable=True))
    op.add_column('training', sa.Column('rocAuc', sa.Float(), nullable=True))
    op.add_column('training', sa.Column('updatedAt', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('training_idModel_fkey'), 'training', type_='foreignkey')
    op.drop_constraint(op.f('training_idParameterTraining_fkey'), 'training', type_='foreignkey')
    op.create_foreign_key(None, 'training', 'dataset', ['idDataset'], ['idDataset'])
    op.drop_column('training', 'idModel')
    op.drop_column('training', 'idParameterTraining')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('idParameterTraining', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('training', sa.Column('idModel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'training', type_='foreignkey')
    op.create_foreign_key(op.f('training_idParameterTraining_fkey'), 'training', 'parameter_training', ['idParameterTraining'], ['idParameterTraining'])
    op.create_foreign_key(op.f('training_idModel_fkey'), 'training', 'model', ['idModel'], ['idModel'])
    op.drop_column('training', 'updatedAt')
    op.drop_column('training', 'rocAuc')
    op.drop_column('training', 'mcc')
    op.drop_column('training', 'valLoss')
    op.drop_column('training', 'trainLoss')
    op.drop_column('training', 'macroAverage')
    op.drop_column('training', 'weightedAverage')
    op.drop_column('training', 'confusionMatrix')
    op.drop_column('training', 'learningRate')
    op.drop_column('training', 'batchSize')
    op.drop_column('training', 'epochs')
    op.drop_column('training', 'kFold')
    op.drop_column('training', 'denseUnits')
    op.drop_column('training', 'dropout2')
    op.drop_column('training', 'dropout1')
    op.drop_column('training', 'LSTMUnits2')
    op.drop_column('training', 'LSTMUnits1')
    op.drop_column('training', 'modelName')
    op.drop_column('training', 'idDataset')
    op.add_column('ratio_data_split', sa.Column('valRatio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ratio_data_split', sa.Column('testRatio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('ratio_data_split', 'trainRatio',
               existing_type=sa.String(length=99),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('ratio_data_split', 'updatedAt')
    op.drop_column('ratio_data_split', 'bestRatio')
    op.drop_column('ratio_data_split', 'f1score')
    op.drop_column('ratio_data_split', 'recall')
    op.drop_column('ratio_data_split', 'precision')
    op.drop_column('ratio_data_split', 'accuracy')
    op.drop_column('ratio_data_split', 'learningRate')
    op.drop_column('ratio_data_split', 'batchSize')
    op.drop_column('ratio_data_split', 'epochs')
    op.drop_column('dataset', 'preprocessingResultPath')
    op.create_table('model',
    sa.Column('idModel', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('LSTMUnits1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('LSTMUnits2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dropout1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dropout2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('denseUnits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idModel', name=op.f('model_pkey'))
    )
    op.create_table('parameter_training',
    sa.Column('idParameterTraining', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('epochs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('batchSize', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('learningRate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idParameterTraining', name=op.f('parameter_training_pkey'))
    )
    op.create_table('preprocessing_training',
    sa.Column('idPreprocessingTraining', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idPreprocessingResult', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('idTraining', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idPreprocessingResult'], ['preprocessing_result.idPreprocessingResult'], name=op.f('preprocessing_training_idPreprocessingResult_fkey')),
    sa.ForeignKeyConstraint(['idTraining'], ['training.idTraining'], name=op.f('preprocessing_training_idTraining_fkey')),
    sa.PrimaryKeyConstraint('idPreprocessingTraining', name=op.f('preprocessing_training_pkey'))
    )
    op.create_table('preprocessing_result',
    sa.Column('idPreprocessingResult', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idDataset', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preprocessingFilePath', sa.VARCHAR(length=999), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idDataset'], ['dataset.idDataset'], name=op.f('preprocessing_result_idDataset_fkey')),
    sa.PrimaryKeyConstraint('idPreprocessingResult', name=op.f('preprocessing_result_pkey'))
    )
    # ### end Alembic commands ###
