"""add column dataName on raw_data

Revision ID: 8c56810c395c
Revises: 2873c9192bbe
Create Date: 2026-06-10 22:51:33.088930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c56810c395c'
down_revision: Union[str, Sequence[str], None] = '2873c9192bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_data', sa.Column('dataName', sa.String(length=99), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_data', 'dataName')
    # ### end Alembic commands ###
