"""ubah nama atribut di tabel admin

Revision ID: 07ab35948a54
Revises: 3fc4557b4594
Create Date: 2026-06-20 08:24:26.789685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07ab35948a54'
down_revision: Union[str, Sequence[str], None] = '3fc4557b4594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('username', sa.String(length=999), nullable=True))
    op.add_column('admin', sa.Column('password', sa.String(length=10), nullable=True))
    op.drop_column('admin', 'passwordAdmin')
    op.drop_column('admin', 'usernameAdmin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('usernameAdmin', sa.VARCHAR(length=999), autoincrement=False, nullable=True))
    op.add_column('admin', sa.Column('passwordAdmin', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('admin', 'password')
    op.drop_column('admin', 'username')
    # ### end Alembic commands ###
