"""add attribute di tabel raw_data dan dataset

Revision ID: 3047bb3c7415
Revises: 8b175cdc0eac
Create Date: 2026-06-28 04:06:52.142978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3047bb3c7415'
down_revision: Union[str, Sequence[str], None] = '8b175cdc0eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('datasetFolderPath', sa.String(length=999), nullable=True))
    op.add_column('dataset', sa.Column('isPreprocessed', sa.Boolean(), nullable=True))
    op.add_column('dataset', sa.Column('landmarkFolderPath', sa.String(length=999), nullable=True))
    op.drop_column('dataset', 'preprocessingResultPath')
    op.drop_column('dataset', 'folderPath')
    op.add_column('raw_data', sa.Column('landmarkFilePath', sa.String(length=999), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_data', 'landmarkFilePath')
    op.add_column('dataset', sa.Column('folderPath', sa.VARCHAR(length=999), autoincrement=False, nullable=True))
    op.add_column('dataset', sa.Column('preprocessingResultPath', sa.VARCHAR(length=999), autoincrement=False, nullable=True))
    op.drop_column('dataset', 'landmarkFolderPath')
    op.drop_column('dataset', 'isPreprocessed')
    op.drop_column('dataset', 'datasetFolderPath')
    # ### end Alembic commands ###
