"""ubah tabel user menjadi tabel admin

Revision ID: 3fc4557b4594
Revises: d712cbe855ac
Create Date: 2026-06-19 23:46:23.286473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fc4557b4594'
down_revision: Union[str, Sequence[str], None] = 'd712cbe855ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('idAdmin', sa.Integer(), nullable=False),
    sa.Column('usernameAdmin', sa.String(length=999), nullable=True),
    sa.Column('passwordAdmin', sa.String(length=10), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idAdmin')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('idUser', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nameUser', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('emailUser', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('passwordUser', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idUser', name=op.f('user_pkey'))
    )
    op.drop_table('admin')
    # ### end Alembic commands ###
