"""add default createdAt

Revision ID: 49a19dba376a
Revises: 8a8a5b78e3e8
Create Date: 2026-06-20 09:17:06.418765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a19dba376a'
down_revision: Union[str, Sequence[str], None] = '8a8a5b78e3e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('idAdmin', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=999), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('idAdmin')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
